<?php

namespace App\Services;

use App\Enums\SkillGroup;
use App\Filament\Resources\Cvs\Schemas\CvForm;
use App\Models\Portfolio;

/**
 * The contract a CV travels under when it leaves the admin for an AI to retune.
 *
 * Emitted as an OpenAPI 3.1 document carrying nothing but `components.schemas`
 * — `paths` is optional in 3.1, and 3.1's schema objects are JSON Schema
 * 2020-12, so this is a plain JSON Schema in a wrapper that drops into a skill.
 *
 * Every constraint here is read from where the application already enforces it
 * (`CvForm::TEXT_LIMIT`, `Portfolio::LOCALES`, `SkillGroup`), so the document
 * handed to an AI cannot describe a CV the form would then reject.
 *
 * Fields are marked `readOnly` for two different reasons. `id` is a guard: the
 * import refuses a document that does not belong to the CV being edited. The
 * identity block is context — it is there so the writing has someone to be
 * about, and it is discarded on the way back in.
 */
class CvSchema
{
    /**
     * The whole document.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'openapi' => '3.1.0',
            'info' => [
                'title' => 'CV content',
                'version' => '1.0.0',
                'description' => 'The shape of a CV exported from the portfolio admin for retuning against a job ad. Generated by `php artisan cv:schema` — edit App\\Services\\CvSchema, not this file.',
            ],
            'components' => [
                'schemas' => [
                    'Cv' => $this->cv(),
                    'WorkExperience' => $this->workExperience(),
                    'Project' => $this->project(),
                    'Education' => $this->education(),
                    'Language' => $this->language(),
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function cv(): array
    {
        return [
            'type' => 'object',
            'description' => implode(' ', [
                'One CV, complete. Return the whole document, not a fragment.',
                'Fields marked readOnly must come back exactly as they were sent.',
                'Everything else may be rewritten, reordered or dropped to suit the',
                'target job ad — but only ever from what is already here: never',
                'invent an employer, a qualification, a project or a skill.',
                'The result is printed to a single A4 page, so length is a real',
                'constraint and the character limits are ceilings, not targets.',
            ]),
            'required' => ['id'],
            'properties' => [
                'id' => [
                    'type' => 'integer',
                    'readOnly' => true,
                    'description' => 'The CV this document was exported from. Copy it back unchanged; the import refuses a document that does not belong to the CV being edited.',
                ],
                'locale' => [
                    'type' => 'string',
                    'enum' => array_keys(Portfolio::LOCALES),
                    'readOnly' => true,
                    'description' => 'The language the CV is written in. Write in this language; do not translate the CV into another.',
                ],
                'full_name' => $this->identity('The person this CV is for.'),
                'avatar_path' => $this->identity('Stored path of the portrait printed on the CV.'),
                'email' => $this->identity('Contact email.', 'email'),
                'phone' => $this->identity('Contact phone number.'),
                'location' => $this->identity('Where the person is based.'),
                'linkedin_url' => $this->identity('LinkedIn profile.', 'uri'),
                'github_url' => $this->identity('GitHub profile.', 'uri'),
                'portfolio_url' => $this->identity('Portfolio address, printed as a QR code.', 'uri'),
                'languages' => [
                    'type' => 'array',
                    'readOnly' => true,
                    'items' => ['$ref' => '#/components/schemas/Language'],
                    'description' => 'Spoken languages. Fixed; copy back unchanged.',
                ],
                'label' => [
                    'type' => 'string',
                    'maxLength' => CvForm::TEXT_LIMIT,
                    'description' => 'A short internal name for this version of the CV, never printed. Name it after the job ad, e.g. "Acme — Senior Backend".',
                ],
                'role' => [
                    'type' => 'string',
                    'maxLength' => CvForm::TEXT_LIMIT,
                    'description' => 'The job title printed under the name. Match the wording the job ad uses where that is an honest description of the same work.',
                ],
                'summary' => [
                    'type' => 'string',
                    'maxLength' => CvForm::TEXT_LIMIT,
                    'contentMediaType' => 'text/html',
                    'description' => implode(' ', [
                        'Profile summary, rendered as rich text.',
                        'Inline HTML only, and only these tags: <p>, <strong>, <em>, <a>.',
                        'Anything else is stripped by the editor.',
                        'The limit counts the markup as well as the words.',
                        'Two lines at most, present tense, specific rather than aspirational.',
                    ]),
                ],
                'stack_highlights' => [
                    'type' => 'array',
                    'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                    'description' => 'The chip row printed above Experience. Five or six technologies, chosen and ordered for the target job ad. Draw only on technologies that appear elsewhere in this document.',
                ],
                'skills' => $this->skills(),
                'experience' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/WorkExperience'],
                    'description' => 'Employment history, most recent first. Reorder or omit entries to suit the target role; never add one.',
                ],
                'projects' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/Project'],
                    'description' => 'Projects worth printing. Select and order them for the target role; never invent or rename one.',
                ],
                'education' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/Education'],
                    'description' => 'Qualifications. Facts: reorder or omit, but never reword or add.',
                ],
            ],
        ];
    }

    /**
     * Skills are printed in groups, and are edited as one list per group, so
     * they travel as an object rather than a flat list carrying a group field.
     *
     * @return array<string, mixed>
     */
    protected function skills(): array
    {
        $groups = [];

        foreach (SkillGroup::cases() as $group) {
            $groups[$group->value] = [
                'type' => 'array',
                'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
            ];
        }

        return [
            'type' => 'object',
            'description' => 'Skills, grouped as they are printed. Within each group, order by relevance to the target job ad and drop what does not earn its space. Never add a skill that was not already somewhere in this document.',
            'properties' => $groups,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function workExperience(): array
    {
        return [
            'type' => 'object',
            'description' => 'One job. Everything but the bullets is a matter of record: do not reword company, title, period or location.',
            'properties' => [
                'company' => $this->fact('Employer name.'),
                'title' => $this->fact('Job title held there.'),
                'period' => $this->fact('When, as printed, e.g. "2024 – Present".'),
                'location' => $this->fact('Where the job was based.'),
                'bullets' => [
                    'type' => 'array',
                    'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                    'description' => 'What was done there, one responsibility or result per line. Rewritable: lead with the work the job ad asks for, keep each line to one idea, and prefer a concrete outcome over a duty. Three to five lines for a recent role, fewer further back.',
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function project(): array
    {
        return [
            'type' => 'object',
            'description' => 'One project, printed as a title and the stack it was built with.',
            'properties' => [
                'title' => $this->fact('Project name.'),
                'stack' => [
                    'type' => 'array',
                    'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                    'description' => 'Technologies it was built with. Reorder to put what the job ad asks for first; never add one that was not used.',
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function education(): array
    {
        return [
            'type' => 'object',
            'description' => 'One qualification. Entirely a matter of record.',
            'properties' => [
                'school' => $this->fact('Institution name.'),
                'degree' => $this->fact('Qualification earned.'),
                'start_year' => $this->fact('Year started, e.g. "2020".'),
                'graduation_year' => $this->fact('Year finished, e.g. "2023".'),
                'location' => $this->fact('Where it was studied.'),
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function language(): array
    {
        return [
            'type' => 'object',
            'readOnly' => true,
            'properties' => [
                'name' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                'level' => ['type' => 'string', 'enum' => CvForm::LANGUAGE_LEVELS],
            ],
        ];
    }

    /**
     * A field the AI reads for context and hands back untouched.
     *
     * @return array<string, mixed>
     */
    protected function identity(string $description, ?string $format = null): array
    {
        return array_filter([
            'type' => 'string',
            'format' => $format,
            'maxLength' => CvForm::TEXT_LIMIT,
            'readOnly' => true,
            'description' => $description.' Fixed; copy back unchanged.',
        ], fn ($value): bool => $value !== null);
    }

    /**
     * A field that may be reordered or dropped along with the entry it belongs
     * to, but never reworded.
     *
     * @return array<string, mixed>
     */
    protected function fact(string $description): array
    {
        return [
            'type' => 'string',
            'maxLength' => CvForm::TEXT_LIMIT,
            'description' => $description.' A matter of record: copy it back unchanged.',
        ];
    }
}
