<?php

namespace App\Services;

use App\Enums\ApplicationMethod;
use App\Enums\ExperienceLevel;
use App\Enums\SkillGroup;
use App\Filament\Resources\Cvs\Schemas\CvForm;
use App\Models\JobApplication;
use App\Models\Portfolio;

/**
 * The contract a CV travels under when it leaves the admin for an AI to retune.
 *
 * Emitted as an OpenAPI 3.1 document carrying nothing but `components.schemas`
 * — `paths` is optional in 3.1, and 3.1's schema objects are JSON Schema
 * 2020-12, so this is a plain JSON Schema in a wrapper that drops into a skill.
 *
 * Every constraint here is read from where the application already enforces it
 * (`CvForm::TEXT_LIMIT`, `Portfolio::LOCALES`, `SkillGroup`), so the document
 * handed to an AI cannot describe a CV the form would then reject.
 *
 * Fields are marked `readOnly` for two different reasons. `id` is a guard: the
 * import refuses a document that does not belong to the CV being edited. The
 * identity block is context — it is there so the writing has someone to be
 * about, and it is discarded on the way back in.
 */
class CvSchema
{
    /**
     * The whole document.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'openapi' => '3.1.0',
            'info' => [
                'title' => 'CV tuning session',
                'version' => '2.0.0',
                'description' => 'The document a CV travels in when it leaves the portfolio admin to be retuned against a job ad, and comes back in. The root is CvExport. Generated by `php artisan cv:schema` — edit App\\Services\\CvSchema, not this file.',
            ],
            'components' => [
                'schemas' => [
                    'CvExport' => $this->export(),
                    'Cv' => $this->cv(),
                    'JobApplication' => $this->jobApplication(),
                    'RequiredSkill' => $this->requiredSkill(),
                    'WorkExperience' => $this->workExperience(),
                    'Project' => $this->project(),
                    'Education' => $this->education(),
                    'Language' => $this->language(),
                ],
            ],
        ];
    }

    /**
     * The root: one retuning of one CV for one job.
     *
     * The two halves arrive together because they are written together — the
     * CV is being reshaped for the ad, so whatever read the ad closely enough
     * to do that already knows everything the application record wants.
     *
     * @return array<string, mixed>
     */
    protected function export(): array
    {
        return [
            'type' => 'object',
            'description' => implode(' ', [
                'A CV and, optionally, the job it is being tuned for.',
                'Return both halves together: the CV to be imported, and the',
                'job application recording where it was sent.',
                'Omit job_application only when no particular job is in play —',
                'a general polish rather than an application.',
            ]),
            'required' => ['cv'],
            'properties' => [
                'cv' => [
                    '$ref' => '#/components/schemas/Cv',
                    'description' => 'The retuned CV.',
                ],
                'job_application' => [
                    '$ref' => '#/components/schemas/JobApplication',
                    'description' => 'The job this CV was tuned for, as far as the ad actually says.',
                ],
            ],
        ];
    }

    /**
     * What is known about the job, which is usually less than one would like.
     *
     * Every field but the company name is optional, and each says so. Job ads
     * routinely omit a seniority, a years figure, or even a location, and the
     * only alternative to leaving those null is inventing them — the one thing
     * this whole exchange is built to prevent.
     *
     * `status` is deliberately absent: a freshly imported application is
     * pending by definition, and what happens to it afterwards is not something
     * the document can know.
     *
     * @return array<string, mixed>
     */
    protected function jobApplication(): array
    {
        return [
            'type' => 'object',
            'description' => implode(' ', [
                'One job applied for. Fill in only what the ad actually states;',
                'leave anything it does not say as null rather than inferring it.',
                'Unlike the CV, this half may quote the ad freely — it is a record',
                'of what was asked for, not a claim about the applicant.',
            ]),
            'required' => ['company'],
            'properties' => [
                'id' => [
                    'type' => 'integer',
                    'readOnly' => true,
                    'description' => 'Present only when this CV already has an application recorded. Copy it back unchanged and the existing record is updated; leave it out and a new one is created.',
                ],
                'company' => [
                    'type' => 'string',
                    'maxLength' => JobApplication::TEXT_LIMIT,
                    'description' => 'Who the application went to. The one field that must be filled in; ask if the ad does not name them.',
                ],
                'title' => [
                    'type' => 'string',
                    'maxLength' => JobApplication::TEXT_LIMIT,
                    'description' => 'The advertised job title, exactly as the ad writes it.',
                ],
                'method' => [
                    'type' => 'string',
                    'enum' => array_column(ApplicationMethod::cases(), 'value'),
                    'description' => 'Where the application was submitted. Ask if it is not obvious; use "ats" for an HR system that is not listed and name it in method_detail.',
                ],
                'method_detail' => [
                    'type' => 'string',
                    'maxLength' => JobApplication::TEXT_LIMIT,
                    'description' => 'Which system, when method is "ats" or "other" — e.g. "Greenhouse", "Teamtailor".',
                ],
                'source_url' => [
                    'type' => 'string',
                    'format' => 'uri',
                    'maxLength' => JobApplication::URL_LIMIT,
                    'description' => 'Link to the posting, if there is one.',
                ],
                'location' => [
                    'type' => 'string',
                    'maxLength' => JobApplication::TEXT_LIMIT,
                    'description' => 'Where the job is, as the ad puts it — including "Remote" or "Hybrid, Budapest".',
                ],
                'experience_level' => [
                    'type' => 'string',
                    'enum' => array_column(ExperienceLevel::cases(), 'value'),
                    'description' => 'The seniority the ad asks for. Null unless the ad names one; do not infer it from the required years.',
                ],
                'required_years' => [
                    'type' => 'integer',
                    'minimum' => 0,
                    'maximum' => 50,
                    'description' => 'Overall years of experience asked for. Null unless the ad gives a figure; for a range, take the lower bound.',
                ],
                'required_skills' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/RequiredSkill'],
                    'description' => 'What the ad asks for, in the order it stresses them. Include skills the CV does not have — this is the ad\'s side of the comparison, and the gaps are the useful part.',
                ],
                'job_ad' => [
                    'type' => 'string',
                    'description' => 'The ad itself, kept verbatim. Postings are taken down; without the original text there is no way to tell later what was applied for. Paste the text as given — do not summarise it.',
                ],
                'notes' => [
                    'type' => 'string',
                    'description' => 'Anything worth remembering that is not a field: a referral, a salary figure mentioned in passing, which parts of the CV were stretched thinnest to fit.',
                ],
                'applied_at' => [
                    'type' => 'string',
                    'format' => 'date',
                    'description' => 'The day the application was sent, as YYYY-MM-DD. Defaults to today when omitted.',
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function requiredSkill(): array
    {
        return [
            'type' => 'object',
            'description' => 'One thing the ad asks for, and how long for, when it says.',
            'required' => ['name'],
            'properties' => [
                'name' => [
                    'type' => 'string',
                    'maxLength' => JobApplication::TEXT_LIMIT,
                    'description' => 'The skill, as the ad names it.',
                ],
                'years' => [
                    'type' => 'integer',
                    'minimum' => 0,
                    'maximum' => 50,
                    'description' => 'Years asked for in this particular skill. Null when the ad does not say — which is most of the time.',
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function cv(): array
    {
        return [
            'type' => 'object',
            'description' => implode(' ', [
                'One CV, complete. Return the whole document, not a fragment.',
                'Fields marked readOnly must come back exactly as they were sent.',
                'Everything else may be rewritten, reordered or dropped to suit the',
                'target job ad — but only ever from what is already here: never',
                'invent an employer, a qualification, a project or a skill.',
                'The result is printed to a single A4 page, so length is a real',
                'constraint and the character limits are ceilings, not targets.',
            ]),
            'required' => ['id'],
            'properties' => [
                'id' => [
                    'type' => 'integer',
                    'readOnly' => true,
                    'description' => 'The CV this document was exported from. Copy it back unchanged; the import refuses a document that does not belong to the CV being edited.',
                ],
                'locale' => [
                    'type' => 'string',
                    'enum' => array_keys(Portfolio::LOCALES),
                    'readOnly' => true,
                    'description' => 'The language the CV is written in. Write in this language; do not translate the CV into another.',
                ],
                'full_name' => $this->identity('The person this CV is for.'),
                'avatar_path' => $this->identity('Stored path of the portrait printed on the CV.'),
                'email' => $this->identity('Contact email.', 'email'),
                'phone' => $this->identity('Contact phone number.'),
                'location' => $this->identity('Where the person is based.'),
                'linkedin_url' => $this->identity('LinkedIn profile.', 'uri'),
                'github_url' => $this->identity('GitHub profile.', 'uri'),
                'portfolio_url' => $this->identity('Portfolio address, printed as a QR code.', 'uri'),
                'languages' => [
                    'type' => 'array',
                    'readOnly' => true,
                    'items' => ['$ref' => '#/components/schemas/Language'],
                    'description' => 'Spoken languages. Fixed; copy back unchanged.',
                ],
                'label' => [
                    'type' => 'string',
                    'maxLength' => CvForm::TEXT_LIMIT,
                    'description' => 'A short internal name for this version of the CV, never printed. Name it after the job ad, e.g. "Acme — Senior Backend".',
                ],
                'role' => [
                    'type' => 'string',
                    'maxLength' => CvForm::TEXT_LIMIT,
                    'description' => 'The job title printed under the name. Match the wording the job ad uses where that is an honest description of the same work.',
                ],
                'summary' => [
                    'type' => 'string',
                    'maxLength' => CvForm::TEXT_LIMIT,
                    'contentMediaType' => 'text/html',
                    'description' => implode(' ', [
                        'Profile summary, rendered as rich text.',
                        'Inline HTML only, and only these tags: <p>, <strong>, <em>, <a>.',
                        'Anything else is stripped by the editor.',
                        'The limit counts the markup as well as the words.',
                        'Two lines at most, present tense, specific rather than aspirational.',
                    ]),
                ],
                'stack_highlights' => [
                    'type' => 'array',
                    'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                    'description' => 'The chip row printed above Experience. Five or six technologies, chosen and ordered for the target job ad. Draw only on technologies that appear elsewhere in this document.',
                ],
                'skills' => $this->skills(),
                'experience' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/WorkExperience'],
                    'description' => 'Employment history, most recent first. Reorder or omit entries to suit the target role; never add one.',
                ],
                'projects' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/Project'],
                    'description' => 'Projects worth printing. Select and order them for the target role; never invent or rename one.',
                ],
                'education' => [
                    'type' => 'array',
                    'items' => ['$ref' => '#/components/schemas/Education'],
                    'description' => 'Qualifications. Facts: reorder or omit, but never reword or add.',
                ],
            ],
        ];
    }

    /**
     * Skills are printed in groups, and are edited as one list per group, so
     * they travel as an object rather than a flat list carrying a group field.
     *
     * @return array<string, mixed>
     */
    protected function skills(): array
    {
        $groups = [];

        foreach (SkillGroup::cases() as $group) {
            $groups[$group->value] = [
                'type' => 'array',
                'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
            ];
        }

        return [
            'type' => 'object',
            'description' => 'Skills, grouped as they are printed. Within each group, order by relevance to the target job ad and drop what does not earn its space. Never add a skill that was not already somewhere in this document.',
            'properties' => $groups,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function workExperience(): array
    {
        return [
            'type' => 'object',
            'description' => 'One job. Everything but the bullets is a matter of record: do not reword company, title, period or location.',
            'properties' => [
                'company' => $this->fact('Employer name.'),
                'title' => $this->fact('Job title held there.'),
                'period' => $this->fact('When, as printed, e.g. "2024 – Present".'),
                'location' => $this->fact('Where the job was based.'),
                'bullets' => [
                    'type' => 'array',
                    'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                    'description' => 'What was done there, one responsibility or result per line. Rewritable: lead with the work the job ad asks for, keep each line to one idea, and prefer a concrete outcome over a duty. Three to five lines for a recent role, fewer further back.',
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function project(): array
    {
        return [
            'type' => 'object',
            'description' => 'One project, printed as a title and the stack it was built with.',
            'properties' => [
                'title' => $this->fact('Project name.'),
                'stack' => [
                    'type' => 'array',
                    'items' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                    'description' => 'Technologies it was built with. Reorder to put what the job ad asks for first; never add one that was not used.',
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function education(): array
    {
        return [
            'type' => 'object',
            'description' => 'One qualification. Entirely a matter of record.',
            'properties' => [
                'school' => $this->fact('Institution name.'),
                'degree' => $this->fact('Qualification earned.'),
                'start_year' => $this->fact('Year started, e.g. "2020".'),
                'graduation_year' => $this->fact('Year finished, e.g. "2023".'),
                'location' => $this->fact('Where it was studied.'),
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    protected function language(): array
    {
        return [
            'type' => 'object',
            'readOnly' => true,
            'properties' => [
                'name' => ['type' => 'string', 'maxLength' => CvForm::TEXT_LIMIT],
                'level' => ['type' => 'string', 'enum' => CvForm::LANGUAGE_LEVELS],
            ],
        ];
    }

    /**
     * A field the AI reads for context and hands back untouched.
     *
     * @return array<string, mixed>
     */
    protected function identity(string $description, ?string $format = null): array
    {
        return array_filter([
            'type' => 'string',
            'format' => $format,
            'maxLength' => CvForm::TEXT_LIMIT,
            'readOnly' => true,
            'description' => $description.' Fixed; copy back unchanged.',
        ], fn ($value): bool => $value !== null);
    }

    /**
     * A field that may be reordered or dropped along with the entry it belongs
     * to, but never reworded.
     *
     * @return array<string, mixed>
     */
    protected function fact(string $description): array
    {
        return [
            'type' => 'string',
            'maxLength' => CvForm::TEXT_LIMIT,
            'description' => $description.' A matter of record: copy it back unchanged.',
        ];
    }
}
